name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout the code'
        uses: actions/checkout@v2

      - name: 'Set up Nodejs'
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: 'Install dependencies'
        run: yarn
